---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: top-level CI
        run: |
          rebar3 ci

      - name: example-level CI
        run: |
          pushd example
          rebar3 ci
          popd

      - name: check formatting
        run: |
          rebar3 fmt --check

      - name: test the example release
        run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          pushd example
          rebar3 release
          _build/default/rel/simpler_cowboy_rest_example/bin/simpler_cowboy_rest_example daemon
          popd
          shelltest tests/example.test
