---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: erlef/setup-beam@75edbb82877ab10edeb12a99c3cf2f0909f3dc87 # v1.20.1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: top-level CI
        run: |
          rebar3 ci

      - name: example-level CI
        run: |
          pushd example
          rebar3 ci
          popd

      - name: check formatting
        run: |
          rebar3 fmt --check

      - name: test the example release
        run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          pushd example
          rebar3 release
          _build/default/rel/simpler_cowboy_rest_example/bin/simpler_cowboy_rest_example daemon
          popd
          shelltest tests/example.test
