---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: erlef/setup-beam@a6e26b22319003294c58386b6f25edbc7336819a # v1.18.0
        with:
          version-type: strict
          version-file: .tool-versions

      - name: top-level CI
        run: |
          rebar3 ci

      - name: example-level CI
        run: |
          pushd example
          rebar3 ci
          popd

      - name: check formatting
        run: |
          rebar3 fmt --check

      - name: test the example release
        run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          pushd example
          rebar3 release
          _build/default/rel/simpler_cowboy_rest_example/bin/simpler_cowboy_rest_example daemon
          popd
          shelltest tests/example.test
