---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          version-type: strict
          version-file: .tool-versions

      - name: top-level CI
        run: |
          rebar3 ci

      - name: example-level CI
        run: |
          pushd example
          rebar3 ci
          popd

      - name: test the example release
        run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          pushd example
          rebar3 release
          _build/default/rel/simpler_cowboy_rest_example/bin/simpler_cowboy_rest_example daemon
          popd
          shelltest tests/example.test
