---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: erlef/setup-beam@0a541161e47ec43ccbd9510053c5f336ca76c2a2 # v1.17.6
        with:
          version-type: strict
          version-file: .tool-versions

      - run: rebar3 ci

      - run: rebar3 fmt --check

      - run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          pushd example
          rebar3 release
          _build/default/rel/simpler_cowboy_rest_example/bin/simpler_cowboy_rest_example daemon
          popd
          shelltest tests/example.test
