---
name: CI

"on": [push, workflow_dispatch]

jobs:
  ci:
    name: CI

    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: erlef/setup-beam@v1.17.5
        with:
          version-type: strict
          version-file: .tool-versions

      - run: rebar3 ci

      - run: rebar3 fmt --check

      - run: |
          sudo apt-get -y update
          sudo apt-get -y install shelltestrunner
          rebar3 release
          _build/default/rel/simpler_cowboy_rest/bin/simpler_cowboy_rest daemon
          shelltest tests/example.test
